name: Auto Branch and PR
on:
  issues:
    types: [assigned]
jobs:
  auto-branch-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Create a branch for the issue
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        ISSUE_BRANCH="issue-${ISSUE_NUMBER}-${ISSUE_TITLE// /-}"
        ISSUE_BRANCH=$(echo $ISSUE_BRANCH | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]-' | cut -c1-63)
        echo "Creating branch $ISSUE_BRANCH"
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
        git checkout -b $ISSUE_BRANCH
        git push -u origin $ISSUE_BRANCH
        echo "ISSUE_BRANCH=$ISSUE_BRANCH" >> $GITHUB_ENV

    - name: Create a pull request
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_REPO: ${{ github.repository }}
      run: |
        gh pr create --repo $GH_REPO --base main --head $ISSUE_BRANCH --title "Fix #${{ github.event.issue.number }} - ${{ github.event.issue.title }}" --body "Closes #${{ github.event.issue.number }}"
